# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
